/*Roles iniciales*/
INSERT INTO [MesaDeAyuda].[dbo].[rol] VALUES (1, 'Administrador' )
INSERT INTO [MesaDeAyuda].[dbo].[rol] VALUES (2, 'Supervisor' )
INSERT INTO [MesaDeAyuda].[dbo].[rol] VALUES (3, 'Tecnico' )
INSERT INTO [MesaDeAyuda].[dbo].[rol] VALUES (4, 'Usuario' )

/*Tipos de ticket iniciales*/
INSERT INTO [MesaDeAyuda].[dbo].[tipoTicket] VALUES (1, 'Incidencia' )
INSERT INTO [MesaDeAyuda].[dbo].[tipoTicket] VALUES (2, 'Solicitud de Servicio' )
INSERT INTO [MesaDeAyuda].[dbo].[tipoTicket] VALUES (3, 'Problemas' )
INSERT INTO [MesaDeAyuda].[dbo].[tipoTicket] VALUES (4, 'Solicitud de cambio' )

/*Estado de Tickets*/
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (1, 'Abierto')
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (2, 'En proceso')
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (3, 'Pendiente')
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (4, 'Resuelto')
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (5, 'Cerrado')
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (6, 'Reabierto')
INSERT INTO [MesaDeAyuda].[dbo].[estadoTicket] VALUES (7, 'Cancelado')

/*Categorías Iniciales*/
INSERT INTO [MesaDeAyuda].[dbo].[categoria] VALUES (1, 'Hardware' )
INSERT INTO [MesaDeAyuda].[dbo].[categoria] VALUES (2, 'Software' )
INSERT INTO [MesaDeAyuda].[dbo].[categoria] VALUES (3, 'Red' )
INSERT INTO [MesaDeAyuda].[dbo].[categoria] VALUES (4, 'Seguridad' )
INSERT INTO [MesaDeAyuda].[dbo].[categoria] VALUES (5, 'Acceso' )
INSERT INTO [MesaDeAyuda].[dbo].[categoria] VALUES (6, 'Servicios' )

/*Subcategorias iniciales*/
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (1, 'Ordenadores de sobremesa y portátiles', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (2, 'Impresoras y escáneres', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (3, 'Dispositivos móviles', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (4, 'Servidores', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (5, 'Equipos de Red', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (6, 'Periféricos', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (7, 'Dispositivos de almacenamiento', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (8, 'Equipos de videoconferencia', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (9, 'Problemas de energía', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (10, 'Docking stations', 1)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (11, 'Aplicaciones de S.O.', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (12, 'Correo Electrónico', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (13, 'Base de datos', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (14, 'Instalación / actualización de software', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (15, 'Licenciamiento', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (16, 'Errores de sistema operativo', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (17, 'Aplicaciones corporativas internas', 2)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (18, 'Problemas de conectividad', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (19, 'Problemas de VPN', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (20, 'Rendimiento lento de Internet/Red', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (21, 'Acceso Wifi', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (22, 'Problemas de LAN cableada', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (23, 'Caídas de red general', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (24, 'Problemas con proxy/firewall', 3)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (25, 'Virus y Malware', 4)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (26, 'Acceso no autorizado', 4)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (27, 'Intentos de Phishing', 4)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (28, 'Gestión de antivirus/EDR', 4)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (29, 'Restablecimiento de contraseñas', 5)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (30, 'Bloqueo de cuentas', 5)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (31, 'Problemas de permiso', 5)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (32, 'Baja de usuarios', 5)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (33, 'Modificación de accesos/roles', 5)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (34, 'Acceso remoto', 6)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (35, 'Interrupción del servicio de correo electrónico', 6)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (36, 'Fallos en la copia de seguridad y recuperación', 6)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (37, 'Configuracion de usuarios', 6)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (38, 'Solicitud de nuevos servicios TI', 6)
INSERT INTO [MesaDeAyuda].[dbo].[subCategoriaTicket] VALUES (39, 'Gestión de respaldos (restore)', 6)

/*Departamento inicial*/
INSERT INTO [MesaDeAyuda].[dbo].[departamento] VALUES (1, 'Administrador', 'tecnico')